// src/utils/seed.js
// Seeds the database with initial teacher account and sample students.
// Run: npm run seed
// WARNING: Clears ALL existing users.

require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });

const mongoose = require('mongoose');
const { MONGO_URI } = require('../config/env');
const User = require('../models/User');

const TEACHER_CODE = 'TEACHER2026';

const SAMPLE_STUDENTS = [
  { name: 'محمد أحمد علي',  code: 'ST2026001', academicYear: 'first-prep'  },
  { name: 'خالد عمر فتحي',  code: 'ST2026002', academicYear: 'first-prep'  },
  { name: 'سارة محمود',      code: 'ST2026003', academicYear: 'first-prep'  },
  { name: 'يوسف كمال',       code: 'ST2026004', academicYear: 'second-prep' },
  { name: 'دينا حسن',        code: 'ST2026005', academicYear: 'second-prep' },
  { name: 'توني جورج',       code: 'ST2026006', academicYear: 'third-prep'  },
  { name: 'مريم سعيد',       code: 'ST2026007', academicYear: 'third-prep'  },
  { name: 'كريم وليد',       code: 'ST2026008', academicYear: 'first-sec'   },
  { name: 'ندى أشرف',        code: 'ST2026009', academicYear: 'second-sec'  },
  { name: 'زياد منصور',      code: 'ST2026010', academicYear: 'second-sec'  },
];

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅  MongoDB connected\n');

    await User.deleteMany({});
    console.log('🗑️   Cleared all users');

    // ── Teacher ───────────────────────────────────────────────────────────────
    // codePlain = plain text (uppercased automatically by schema)
    // codeHash  = generated by pre-save hook automatically
    await User.create({
      name:      'المعلم الرئيسي',
      codePlain: TEACHER_CODE,
      role:      'teacher',
    });
    console.log(`👨‍🏫  Teacher created  |  Code: ${TEACHER_CODE}`);

    // ── Students ──────────────────────────────────────────────────────────────
    for (const s of SAMPLE_STUDENTS) {
      await User.create({
        name:         s.name,
        codePlain:    s.code,
        role:         'student',
        academicYear: s.academicYear,
      });
      console.log(`👨‍🎓  ${s.name}  |  ${s.code}  |  ${s.academicYear}`);
    }

    console.log('\n✅  Seed done!');
    console.log('──────────────────────────────');
    console.log('Teacher:  TEACHER2026');
    console.log('Students: ST2026001 → ST2026010');
    console.log('──────────────────────────────\n');

    process.exit(0);
  } catch (err) {
    console.error('❌  Seed failed:', err.message);
    process.exit(1);
  }
};

seed();
